### ISSUE TITLE
How to use purgeCache

### ISSUE THREAD

**Issue by ozbillwang** [commerceblock/serverless-single-page-app-plugin#1]
I have successfully deploy with this serverless plugin and define the Outputs as below: 

```
  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [ WebAppCloudFrontDistribution, DomainName ]
```
but when run with `sls purgeCache`, I got this error:

```
  Type Error ---------------------------------------------

  Cannot read property 'OutputValue' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

```

I can run `sls deploy`, `sls syncToS3` and `sls domainInfo` successfully.

Any help?
